---

- hosts: all
  become: true

  - name: update the repositroy index
    apt:
      update_cache: yes

  - name: Remove apache2 package
    apt:
      name: apache2
      state: absent

  - name: remove php support
    apt:
      name: libapache2-mod-php
      state: absent
      